# Project: JuegoWari
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"D:/Programacion de videojuegos/Recursos/Dev-CppPortable/Dev-Cpp/MinGW64/lib" -L"D:/Programacion de videojuegos/Recursos/Dev-CppPortable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -L"C:/SFML-2.4.1/lib" -L"D:/Programacion de videojuegos/Recursos/SFML-2.4.1/lib" -mwindows -lsfml-audio -lsfml-graphics -lsfml-system -lsfml-window
INCS     = -I"D:/Programacion de videojuegos/Recursos/Dev-CppPortable/Dev-Cpp/MinGW64/include" -I"D:/Programacion de videojuegos/Recursos/Dev-CppPortable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Programacion de videojuegos/Recursos/Dev-CppPortable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Programacion de videojuegos/Recursos/SFML-2.4.1/include"
CXXINCS  = -I"D:/Programacion de videojuegos/Recursos/Dev-CppPortable/Dev-Cpp/MinGW64/include" -I"D:/Programacion de videojuegos/Recursos/Dev-CppPortable/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/Programacion de videojuegos/Recursos/Dev-CppPortable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/Programacion de videojuegos/Recursos/Dev-CppPortable/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"D:/Programacion de videojuegos/Recursos/SFML-2.4.1/include"
BIN      = JuegoWari.exe
CXXFLAGS = $(CXXINCS) -std=c++11
CFLAGS   = $(INCS) -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)
